### ISSUE TITLE
ERX 安装时找不到OBFS-Server

### ISSUE THREAD

**Issue by nimotsang** [ld0891/ubnt-simple-obfs#1]
你好，我在ERX上安装时报错，提示如下：

root@EdgeRouter:/usr# dpkg -i simple-obfs_0.0.3-1_mipsel.deb
Selecting previously unselected package simple-obfs.
(Reading database ... 34608 files and directories currently installed.)
Unpacking simple-obfs (from simple-obfs_0.0.3-1_mipsel.deb) ...
Setting up simple-obfs (0.0.3-1) ...
Failed to set capabilities on file `/usr/bin/obfs-server' (Operation not support
ed)
 
dpkg: error processing simple-obfs (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 simple-obfs
root@EdgeRouter:/usr#

**Comment by ld0891** [comment]
这是因为安装后脚本里会进行权限配置，而 UBNT 用的 aufs 文件系统不支持这个特性。  
正常使用应该没有问题。

**Comment by nimotsang** [comment]
非常感谢你的回复
